### ISSUE TITLE
keepinputtext setting not working as expected

### ISSUE THREAD

**Issue by scottr1634** [GenieClient/genie3#2]
Normally when `#config keepinputtext true` is set, after submitting a command by pressing enter the command text will remain in the input field. This is not currently working for me.

![image](https://user-images.githubusercontent.com/32966288/147695896-7152d244-73b4-4e87-a882-cd3bf019308f.png)

**Comment by jingounchained** [comment]
this appears to be working, no other reports, this was likely resolved by an early fix which addressed the input textbox selection
