### ISSUE TITLE
Globals.cs Line 17 Compiler Error

### ISSUE THREAD

**Issue by arc118** [GenieClient/genie3#20]
private Config _Config = new();

should be

private Config _Config = new Config();

![issue](https://user-images.githubusercontent.com/96793326/147805898-cbe6947c-a2af-420d-ad0a-968797b2ee85.png)

**Comment by jingounchained** [comment]
Fixed in newest release
https://github.com/GenieClient/genie3/releases/tag/3.6.1.1
