### ISSUE TITLE
Maps-Issue-Not Centering

### ISSUE THREAD

**Issue by monil2233** [GenieClient/genie3#21]
Map Not Resize/Centering on update

**Comment by RskyRz6822** [comment]
![map](https://user-images.githubusercontent.com/97002936/147892674-96ace86c-e4eb-41db-8bae-bccf3117394d.jpg)

adding screenshot for visual

**Comment by jingounchained** [comment]
fixed in latest release
https://github.com/GenieClient/genie3/releases/tag/3.6.1.2
