### ISSUE TITLE
Game window is being spammed with >

### ISSUE THREAD

**Issue by d-stafford** [GenieClient/genie3#30]
`&gt;` is being sent back from the game when nothing else is between the xml tags. You end up getting a screen that appears like:
&gt;
&gt;
&gt;
&gt;
&gt;
We need to stop sending the `&gt;` to the game window if there is nothing to update.

**Comment by d-stafford** [comment]
A temporary solution is to add a gag ^[>]

**Comment by jingounchained** [comment]
I've updated the latest release with a resolution to this
https://github.com/GenieClient/genie3/releases/tag/3.6.1
