### ISSUE TITLE
Gag list not loading

### ISSUE THREAD

**Issue by kryptonomica** [GenieClient/genie3#36]
Gag list isn't loading. Regardless of how gags are added, either manually from the configuration window or via the #gag command. I'll save the list. However if I click Load it will give me an error of "Load Failed!". If I close and relaunch Genie the gag list will appear blank and gags won't work.

**Comment by jingounchained** [comment]
Fixed in the next release and slipped the fix into the current executable packaged here
https://github.com/GenieClient/genie3/releases/tag/3.6.1.3
