### ISSUE TITLE
Genie crashes with ntdll.dll error.

### ISSUE THREAD

**Issue by kryptonomica** [GenieClient/genie3#40]
Experienced several crashes of Genie with the error below. 

Log Name:      Application
Source:        Application Error
Date:          1/11/2022 1:33:53 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      computer
Description:
Faulting application name: Genie.exe, version: 3.6.1.3, time stamp: 0x61dc4379
Faulting module name: ntdll.dll, version: 10.0.19041.1288, time stamp: 0xa280d1d6
Exception code: 0xc00000fd
Fault offset: 0x000000000001998e
Faulting process id: 0x810
Faulting application start time: 0x01d80705420279a2
Faulting application path: C:\Program Files (x86)\Genie Client 3\Genie.exe
Faulting module path: C:\windows\SYSTEM32\ntdll.dll
Report Id: d02466a9-8a57-4191-8236-934eb97e1a12
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-01-11T19:33:53.2781476Z" />
    <EventRecordID>4078</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>MININT-AH7CVM6</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Genie.exe</Data>
    <Data>3.6.1.3</Data>
    <Data>61dc4379</Data>
    <Data>ntdll.dll</Data>
    <Data>10.0.19041.1288</Data>
    <Data>a280d1d6</Data>
    <Data>c00000fd</Data>
    <Data>000000000001998e</Data>
    <Data>810</Data>
    <Data>01d80705420279a2</Data>
    <Data>C:\Program Files (x86)\Genie Client 3\Genie.exe</Data>
    <Data>C:\windows\SYSTEM32\ntdll.dll</Data>
    <Data>d02466a9-8a57-4191-8236-934eb97e1a12</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by jingounchained** [comment]
When does this occur?

**Comment by kryptonomica** [comment]
Unsure when it was happening because I was typically AFK when it died. I'm using Genie 4 exclusively now without issue, so I'm closing the issue.
