### ISSUE TITLE
Combat does not get autologged

### ISSUE THREAD

**Issue by hubConnect** [GenieClient/genie3#6]
`You get a tyrium svidaw sis from inside your hitman's backpack.
J> lob XXXX
JR> `

Since the addition of combat windows, autologging for combat has been broken.

**Comment by scottr1634** [comment]
I think we will need to add combat to the existing XML parsing to tackle this. This bug is not specific to this version of genie but it would be great to address asap.

**Comment by hubConnect** [comment]
Agreed - it's definitely been a long standing frustration.
