### ISSUE TITLE
Game window autoscroll

### ISSUE THREAD

**Issue by scottr1634** [GenieClient/genie3#9]
The game window doesn't always scroll down to the bottom making it hard to see what's happening in game.

**Comment by jingounchained** [comment]
I have not observed this issue. Can you verify this is still occurring in the latest build?
https://github.com/GenieClient/genie3/releases/tag/3.6.1.1

**Comment by jingounchained** [comment]
no other reports of this issue, it was likely resolved by one of the early updates that addressed window selection
